### ISSUE TITLE
Error in custom function causes it to be run a second time

### ISSUE THREAD

**Issue by georgecrawford** [webdriverio/wdio-sync#17]
As mentioned in https://github.com/webdriverio/wdio-sync/pull/12:

```js
		browser.addCommand('mycustomfunc', function () {
			console.log('mycustomfunc running now', Error().stack);
			throw Error('mycustomfunc error');
		});
```
prints:
```js
mycustomfunc running now Error
    at Error (native)
    at Object.<anonymous> (/Users/george/Shell/sandboxes/ft-app-webdriverio/build/test/specs/startup.js:43:37)
    at /Users/george/Sites/Git/wdio-sync/build/index.js:187:29
mycustomfunc running now Error
    at Error (native)
    at Object.<anonymous> (/Users/george/Shell/sandboxes/ft-app-webdriverio/build/test/specs/startup.js:43:37)
    at /Users/george/Sites/Git/wdio-sync/build/index.js:187:29
```
(two calls here: https://github.com/webdriverio/wdio-sync/blob/master/index.js#L60). Also note the stack trace isn't very useful here, and should be improved if possible.

An `async` custom function is similarly called twice:
```js
mycustomfunc running now Error
    at Error (native)
    at Object.async (/Users/george/Shell/sandboxes/ft-app-webdriverio/build/test/specs/startup.js:43:37)
    at Object.<anonymous> (/Users/george/Sites/Git/wdio-sync/build/index.js:348:30)
    at /Users/george/Sites/Git/wdio-sync/build/index.js:250:23
    at process._tickCallback (node.js:379:9)
mycustomfunc running now Error
    at Error (native)
    at Object.async (/Users/george/Shell/sandboxes/ft-app-webdriverio/build/test/specs/startup.js:43:37)
    at Object.<anonymous> (/Users/george/Sites/Git/wdio-sync/build/index.js:348:30)
    at Object.mycustomfunc (/Users/george/Sites/Git/wdio-sync/build/index.js:273:23)
    at Context.<anonymous> (/Users/george/Shell/sandboxes/ft-app-webdriverio/build/test/specs/startup.js:78:11)
    at /Users/george/Sites/Git/wdio-sync/build/index.js:401:24
```
(first call here: https://github.com/webdriverio/wdio-sync/blob/master/index.js#L115, second call here: https://github.com/webdriverio/wdio-sync/blob/master/index.js#L143).

Whichever way we handle failures when calling a future, I don't think the custom function should be called twice - I think that's unexpected from a user's point of view.

**Comment by christian-bromann** [comment]
Good catch. We should check the error message here to only run it twice when the future call breaks.

**Comment by georgecrawford** [comment]
What kind of code would cause the future call to break?

**Comment by christian-bromann** [comment]
Of you call `Future.wait()` not within the same event loop where you call `Fiber(...).run()` it breaks. This happens for instance when you do this:
```js
browser.someCommand(); // works
process.nextTick(function() {
    browser.someCommand(); // breaks
})
```

**Comment by georgecrawford** [comment]
OK, I'll try that
